/* =========================================================================
   منظومة مركز تمكين — Core: design tokens, i18n, seed data, icons, helpers
   Exposes window.TC
   ========================================================================= */
(function () {
  // ----------------------------------------------------------------- THEME
  const theme = {
    cream:     '#F4EFE3',   // page background
    creamDeep: '#EDE5D3',   // alt / inset surfaces
    paper:     '#FCFAF3',   // card surface
    paperAlt:  '#F8F3E8',
    ink:       '#473C28',   // darkest heading
    brown:     '#6E5B3D',   // body brown
    primary:   '#8C6F47',   // brand primary
    primaryDeep:'#6B5435',
    tan:       '#A98F66',
    gold:      '#B68A3E',   // accent
    goldSoft:  '#E9D9B6',
    line:      '#E2D7BF',
    lineSoft:  '#EDE5D2',
    muted:     '#9B8C70',
    mutedSoft: '#B6A887',
    charcoal:  '#322E26',   // topbar / footer
    white:     '#FFFFFF',
    // status
    okBg:'#E7EFE4', ok:'#5C8A55',
    warnBg:'#F5ECD3', warn:'#B08A2E',
    badBg:'#F4E4DB', bad:'#B5664A',
    infoBg:'#E4ECF1', info:'#577E94',
  };

  // helper to get accent for role
  const roleColor = (role) => ({
    director:'#6B5435', management:'#8C6F47', teacher:'#A98F66', student:'#B68A3E'
  })[role] || theme.primary;

  // ----------------------------------------------------------------- I18N
  const STR = {
    // chrome
    centerName:{ar:'مركز تمكين',en:'Tamkeen Center'},
    centerSlogan:{ar:'نحو الريادة والتطوير',en:'Towards Leadership & Development'},
    login:{ar:'تسجيل الدخول',en:'Login'},
    logout:{ar:'تسجيل الخروج',en:'Logout'},
    langLabel:{ar:'English',en:'العربية'},
    home:{ar:'الرئيسية',en:'Home'},
    aboutCenter:{ar:'عن المركز',en:'About'},
    management:{ar:'إدارة المركز',en:'Leadership'},
    eServices:{ar:'الخدمات الإلكترونية',en:'E-Services'},
    diplomas:{ar:'الدبلومات',en:'Diplomas'},
    back:{ar:'العودة',en:'Back'},
    cancel:{ar:'إلغاء',en:'Cancel'},
    save:{ar:'حفظ',en:'Save'},
    add:{ar:'إضافة',en:'Add'},
    edit:{ar:'تعديل',en:'Edit'},
    delete:{ar:'حذف',en:'Delete'},
    search:{ar:'بحث…',en:'Search…'},
    send:{ar:'إرسال',en:'Send'},
    close:{ar:'إغلاق',en:'Close'},
    // hero
    heroEyebrow:{ar:'مركز تعليمي معتمد',en:'Accredited Learning Center'},
    heroTitle1:{ar:'العلم النافع، والتطبيق الراسخ',en:'Beneficial Knowledge, Lasting Practice'},
    heroBody1:{ar:'منظومة تعليمية متكاملة تجمع بين أصالة العلوم الشرعية وجودة الإدارة الحديثة، لإعداد جيلٍ متمكّن.',en:'An integrated educational system uniting authentic scholarship with modern administration to prepare a capable generation.'},
    heroTitle2:{ar:'دبلومات متخصّصة بإشراف نخبة',en:'Specialized Diplomas, Elite Supervision'},
    heroBody2:{ar:'برامج معتمدة في السنة النبوية واللغة العربية والتمريض، بمناهج عملية وكادر مؤهّل.',en:'Accredited programs in Prophetic Sunnah, Arabic, and Nursing — practical curricula and qualified staff.'},
    heroTitle3:{ar:'بوابتك الرقمية للتعلّم',en:'Your Digital Gateway to Learning'},
    heroBody3:{ar:'سجّل، تابع جداولك وواجباتك ودرجاتك، وتواصل مع معلّميك — كل ذلك من مكان واحد.',en:'Register, follow your schedule, assignments and grades, and reach your teachers — all in one place.'},
    ctaRegister:{ar:'سجّل الآن',en:'Register Now'},
    ctaExplore:{ar:'استكشف الدبلومات',en:'Explore Diplomas'},
    bannerText:{ar:'التسجيل مفتوح للفصل الدراسي الجديد  •  دبلوم السنة النبوية  •  دبلوم اللغة العربية  •  دبلوم التمريض  •  مقاعد محدودة',en:'Registration open for the new term  •  Prophetic Sunnah Diploma  •  Arabic Language Diploma  •  Nursing Diploma  •  Limited seats'},
    // content section
    whyTitle:{ar:'لماذا مركز تمكين؟',en:'Why Tamkeen Center?'},
    whySub:{ar:'بيئة تعليمية متكاملة تُعنى بالطالب من أول يوم حتى التخرّج',en:'A complete environment caring for the student from day one to graduation'},
    galleryTitle:{ar:'من مركز تمكين',en:'From Tamkeen Center'},
    gallerySub:{ar:'لمحات من أنشطة المركز وفعالياته ولقاءاته العلمية',en:'Glimpses of our activities, events and academic gatherings'},
    watchVideo:{ar:'تعرّف على المركز',en:'Get to know the center'},
    statStudents:{ar:'طالب وطالبة',en:'Students'},
    statTeachers:{ar:'معلم ومعلمة',en:'Instructors'},
    statPrograms:{ar:'برامج معتمدة',en:'Accredited Programs'},
    statYears:{ar:'سنوات من العطاء',en:'Years of Service'},
    feat1T:{ar:'مناهج معتمدة',en:'Accredited Curricula'},
    feat1B:{ar:'برامج مبنية على معايير علمية دقيقة ومراجعة من متخصصين.',en:'Programs built on rigorous academic standards, reviewed by specialists.'},
    feat2T:{ar:'متابعة رقمية',en:'Digital Follow-up'},
    feat2B:{ar:'جداول وواجبات ودرجات وإشعارات في منصة واحدة سهلة.',en:'Schedules, assignments, grades and alerts in one simple platform.'},
    feat3T:{ar:'كادر مؤهّل',en:'Qualified Staff'},
    feat3B:{ar:'نخبة من المعلمين والإداريين بخبرات تربوية طويلة.',en:'A select team of teachers and administrators with deep experience.'},
    feat4T:{ar:'بيئة محفّزة',en:'Inspiring Setting'},
    feat4B:{ar:'تقدير للسلوك والانضباط ودعم مستمر لكل طالب.',en:'Recognition of conduct and discipline with continuous support.'},
    // about page
    aboutTitle:{ar:'عن مركز تمكين',en:'About Tamkeen Center'},
    aboutLead:{ar:'مركز تعليمي يسعى إلى إعداد جيلٍ متمكّن علمياً وعملياً، بالجمع بين أصالة المعرفة وحداثة الأداة.',en:'A learning center dedicated to preparing a generation empowered in knowledge and practice — uniting authentic learning with modern tools.'},
    visionT:{ar:'رؤيتنا',en:'Our Vision'},
    visionB:{ar:'أن نكون مرجعاً رائداً في التعليم المتخصّص، نُخرّج كفاءات تخدم مجتمعها بعلمٍ وأمانة.',en:'To be a leading reference in specialized education, graduating talents that serve society with knowledge and integrity.'},
    missionT:{ar:'رسالتنا',en:'Our Mission'},
    missionB:{ar:'تقديم برامج تعليمية معتمدة، ببيئة محفّزة وكادرٍ مؤهّل وأدوات رقمية تواكب العصر.',en:'To deliver accredited programs in an inspiring environment with qualified staff and modern digital tools.'},
    valuesT:{ar:'قيمنا',en:'Our Values'},
    val1:{ar:'الإتقان',en:'Mastery'}, val2:{ar:'الأمانة',en:'Integrity'}, val3:{ar:'الانضباط',en:'Discipline'}, val4:{ar:'الإحسان',en:'Excellence'},
    // management/leadership page
    mgmtTitle:{ar:'إدارة المركز',en:'Center Leadership'},
    mgmtSub:{ar:'فريقٌ قياديٌّ متميّز يقود رحلة التطوير والنمو',en:'A distinguished leadership team driving development and growth'},
    specialization2:{ar:'التخصص',en:'Specialization'},
    // e-services
    esTitle:{ar:'الخدمات الإلكترونية',en:'E-Services'},
    esSub:{ar:'بوابات الدخول والخدمات الرقمية لمنسوبي المركز',en:'Login portals and digital services for our members'},
    esStudent:{ar:'بوابة الطالب',en:'Student Portal'},
    esStudentB:{ar:'الجداول والواجبات والدرجات وصندوق الوارد.',en:'Schedules, assignments, grades and inbox.'},
    esTeacher:{ar:'بوابة المعلم',en:'Teacher Portal'},
    esTeacherB:{ar:'إدارة الطلاب والتوكيلات ومشاركة المحتوى.',en:'Manage students, delegations and shared content.'},
    esAdmin:{ar:'بوابة الإدارة',en:'Admin Portal'},
    esAdminB:{ar:'إدارة المنظومة والجداول والإعلانات.',en:'Manage the system, schedules and announcements.'},
    esRegister:{ar:'تسجيل طالب جديد',en:'New Student Registration'},
    esRegisterB:{ar:'قدّم طلب التحاقك ببرامج المركز.',en:'Submit your application to our programs.'},
    enter:{ar:'دخول',en:'Enter'},
    // diplomas
    dipTitle:{ar:'الدبلومات والبرامج',en:'Diplomas & Programs'},
    dipSub:{ar:'برامج معتمدة تجمع بين العمق العلمي والتطبيق العملي',en:'Accredited programs combining academic depth with practical application'},
    dipDuration:{ar:'المدة',en:'Duration'},
    dipCredits:{ar:'الساعات',en:'Credit Hours'},
    dipDays:{ar:'أيام الدراسة',en:'Study Days'},
    applyNow:{ar:'قدّم طلبك',en:'Apply Now'},
    // footer
    footerAbout:{ar:'مركز تعليمي معتمد يقدّم برامج متخصصة في العلوم الشرعية واللغة العربية والتمريض.',en:'An accredited center offering specialized programs in Islamic studies, Arabic and nursing.'},
    quickLinks:{ar:'روابط سريعة',en:'Quick Links'},
    contact:{ar:'تواصل معنا',en:'Contact'},
    rights:{ar:'جميع الحقوق محفوظة لمركز تمكين',en:'All rights reserved — Tamkeen Center'},
    // ---- AUTH
    welcome:{ar:'مرحباً بك في مركز تمكين',en:'Welcome to Tamkeen Center'},
    chooseOption:{ar:'اختر الخيار المناسب للمتابعة',en:'Choose an option to continue'},
    regStudent:{ar:'طالب مسجّل',en:'Registered Student'},
    regStudentB:{ar:'سجّل دخولك للوصول إلى حسابك',en:'Sign in to access your account'},
    newStudent:{ar:'طالب جديد',en:'New Student'},
    newStudentB:{ar:'قدّم طلب تسجيل جديد للانضمام',en:'Submit a new registration request'},
    staff:{ar:'معلم أو إداري',en:'Teacher or Admin'},
    staffB:{ar:'دخول الكادر التعليمي والإداري',en:'Staff and admin portal access'},
    accessKey:{ar:'مفتاح الدخول',en:'Access Key'},
    passKey:{ar:'كلمة المرور',en:'Password'},
    accessKeyPh:{ar:'أدخل مفتاح الدخول الخاص بك',en:'Enter your access key'},
    passKeyPh:{ar:'أدخل كلمة المرور',en:'Enter your password'},
    enterCreds:{ar:'أدخل بيانات الدخول الخاصة بك',en:'Enter your credentials'},
    loginAs:{ar:'تسجيل الدخول',en:'Login as'},
    loggingIn:{ar:'جاري الدخول…',en:'Logging in…'},
    student:{ar:'طالب',en:'Student'},
    teacher:{ar:'معلم',en:'Teacher'},
    admin:{ar:'إداري',en:'Administrator'},
    director:{ar:'مدير المركز',en:'Director'},
    chooseAccount:{ar:'اختر نوع الحساب',en:'Choose Account Type'},
    teacherPortalDesc:{ar:'للوصول إلى منصة التدريس',en:'Access teaching platform'},
    adminPortalDesc:{ar:'للوصول إلى لوحة التحكم الإدارية',en:'Access administrative panel'},
    quickLoginHint:{ar:'دخول سريع للعرض (بيانات تجريبية)',en:'Quick demo login (sample accounts)'},
    badCreds:{ar:'مفتاح الدخول أو كلمة المرور غير صحيحة',en:'Invalid access key or password'},
    roleMismatch:{ar:'هذا الحساب لا ينتمي لهذا القسم',en:'This account does not belong to this section'},
    // registration form
    regFormTitle:{ar:'نموذج تسجيل طالب جديد',en:'New Student Registration'},
    regFormSub:{ar:'الرجاء ملء البيانات التالية بدقة',en:'Please fill in the following accurately'},
    secPersonal:{ar:'أولاً: البيانات الشخصية',en:'1. Personal Information'},
    secContact:{ar:'ثانياً: بيانات التواصل',en:'2. Contact Information'},
    secQual:{ar:'ثالثاً: المؤهل العلمي',en:'3. Academic Qualification'},
    secProgram:{ar:'رابعاً: بيانات التسجيل في الدبلوم',en:'4. Diploma Registration'},
    secAttach:{ar:'المرفقات المطلوبة',en:'Required Attachments'},
    fullName:{ar:'الاسم الرباعي',en:'Full Name'},
    idNumber:{ar:'رقم الهوية',en:'ID Number'},
    gender:{ar:'الجنس',en:'Gender'}, male:{ar:'ذكر',en:'Male'}, female:{ar:'أنثى',en:'Female'},
    birthPlace:{ar:'مكان الميلاد',en:'Birth Place'},
    birthDate:{ar:'تاريخ الميلاد',en:'Date of Birth'},
    maritalStatus:{ar:'الحالة الاجتماعية',en:'Marital Status'},
    single:{ar:'أعزب',en:'Single'}, married:{ar:'متزوج',en:'Married'}, other:{ar:'أخرى',en:'Other'},
    nationality:{ar:'الجنسية',en:'Nationality'},
    residence:{ar:'مقر الإقامة',en:'Residence'},
    phone:{ar:'رقم الجوال',en:'Phone'},
    email:{ar:'البريد الإلكتروني',en:'Email'},
    workplace:{ar:'جهة العمل (إن وجد)',en:'Workplace (if any)'},
    jobTitle:{ar:'المسمى الوظيفي',en:'Job Title'},
    lastQual:{ar:'آخر مؤهل علمي',en:'Last Qualification'},
    specialization:{ar:'التخصص',en:'Specialization'},
    qualProvider:{ar:'الجهة المانحة',en:'Qualification Provider'},
    gradYear:{ar:'سنة التخرج',en:'Graduation Year'},
    programName:{ar:'اسم البرنامج/الدبلوم',en:'Program / Diploma'},
    studyDays:{ar:'أيام الدراسة',en:'Study Days'},
    howHeard:{ar:'كيف سمعت عن المركز؟',en:'How did you hear about us?'},
    chooseOpt:{ar:'اختر…',en:'Select…'},
    hsCert:{ar:'صورة الشهادة الثانوية',en:'High School Certificate'},
    personalPhoto:{ar:'صورة شخصية (خلفية بيضاء)',en:'Personal Photo (white background)'},
    recommendation:{ar:'تزكية علمية',en:'Academic Recommendation'},
    addCerts:{ar:'شهادات إضافية (اختياري)',en:'Additional Certificates (optional)'},
    pledge:{ar:'أتعهّد بصحة جميع البيانات المذكورة أعلاه، والالتزام بالمواعيد واللوائح التي ينص عليها المركز.',en:'I pledge that all information above is correct, and I commit to the center\'s schedules and regulations.'},
    notes:{ar:'ملاحظات إضافية',en:'Additional Notes'},
    submitApp:{ar:'إرسال الطلب',en:'Submit Application'},
    fillRequired:{ar:'الرجاء ملء جميع الحقول المطلوبة (*)',en:'Please fill all required fields (*)'},
    appSent:{ar:'تم إرسال طلب التسجيل بنجاح! ستتم مراجعته والرد قريباً.',en:'Application submitted! It will be reviewed shortly.'},
    // ---- DASHBOARD common
    inbox:{ar:'صندوق الوارد',en:'Inbox'},
    inboxEmpty:{ar:'صندوق الوارد فارغ',en:'Inbox is empty'},
    inboxEmptyB:{ar:'ستظهر هنا الملفات والجداول المرسلة إليك',en:'Files and schedules sent to you appear here'},
    unread:{ar:'غير مقروء',en:'unread'},
    item:{ar:'عنصر',en:'items'},
    from:{ar:'من',en:'From'},
    schedule:{ar:'جدول',en:'Schedule'},
    file:{ar:'ملف',en:'File'},
    markRead:{ar:'تحديد كمقروء',en:'Mark read'},
    downloadExcel:{ar:'تنزيل Excel',en:'Download Excel'},
    downloadFile:{ar:'تحميل الملف',en:'Download'},
    studentPanel:{ar:'لوحة الطالب',en:'Student Panel'},
    teacherPanel:{ar:'لوحة المعلم',en:'Teacher Panel'},
    adminPanel:{ar:'لوحة الإدارة',en:'Admin Panel'},
    directorPanel:{ar:'لوحة مدير المركز',en:'Director Panel'},
    // student
    myGrades:{ar:'درجاتي',en:'My Grades'},
    myAssignments:{ar:'واجباتي',en:'My Assignments'},
    myProfile:{ar:'ملفي الشخصي',en:'My Profile'},
    gradeRecord:{ar:'سجل الدرجات',en:'Grade Record'},
    noGrades:{ar:'لا توجد درجات بعد',en:'No grades yet'},
    noGradesB:{ar:'ستظهر درجاتك هنا عند إدخالها',en:'Your grades will appear once entered'},
    subject:{ar:'المادة',en:'Subject'},
    score:{ar:'الدرجة',en:'Score'},
    noAssignments:{ar:'لا توجد واجبات',en:'No assignments'},
    noAssignmentsB:{ar:'ستظهر واجباتك هنا عند توكيلها',en:'Assignments appear here when assigned'},
    pending:{ar:'معلّق',en:'Pending'},
    submitted:{ar:'مُسلّم',en:'Submitted'},
    graded:{ar:'مُصحّح',en:'Graded'},
    due:{ar:'الموعد',en:'Due'},
    grade:{ar:'الدرجة',en:'Grade'},
    submitWork:{ar:'تسليم الواجب',en:'Submit Work'},
    behavior:{ar:'نقاط السلوك',en:'Behavior'},
    grades:{ar:'الدرجات',en:'Grades'},
    assignments:{ar:'الواجبات',en:'Assignments'},
    academicYear:{ar:'البرنامج/السنة',en:'Program / Year'},
    joined:{ar:'تاريخ التسجيل',en:'Joined'},
    notSet:{ar:'غير محدد',en:'Not set'},
    mySchedule:{ar:'جدولي',en:'My Schedule'},
    // teacher
    delegatedTasks:{ar:'المهام الموكلة',en:'Delegated Tasks'},
    cloudSystem:{ar:'نظام السحابة',en:'Cloud System'},
    myStudents:{ar:'طلابي',en:'My Students'},
    studentsPage:{ar:'صفحة الطلاب',en:'Students'},
    noTasks:{ar:'لا توجد مهام موكلة حالياً',en:'No delegated tasks currently'},
    tasksFromAdmin:{ar:'المهام الموكلة من الإدارة',en:'Tasks Delegated by Admin'},
    active:{ar:'نشطة',en:'Active'},
    completed:{ar:'مكتملة',en:'Completed'},
    dropFiles:{ar:'اسحب الملفات هنا',en:'Drop files here'},
    orAttach:{ar:'أو أرفق ملفاً من جهازك',en:'Or attach a file'},
    attachFile:{ar:'أرفق ملف',en:'Attach File'},
    clearAll:{ar:'إزالة الكل',en:'Clear All'},
    selectStudent:{ar:'اختر طالباً من القائمة لعرض تفاصيله',en:'Select a student to view details'},
    noDelegated:{ar:'لا يوجد طلاب موكل بهم',en:'No delegated students'},
    addGrade:{ar:'إضافة درجة',en:'Add Grade'},
    assignHw:{ar:'توكيل واجب',en:'Assign Homework'},
    assign:{ar:'توكيل',en:'Assign'},
    hwTitle:{ar:'عنوان الواجب',en:'Homework title'},
    // management
    teachers:{ar:'المعلمين',en:'Teachers'},
    admins:{ar:'الإداريين',en:'Admins'},
    schedules:{ar:'الجداول',en:'Schedules'},
    createSchedules:{ar:'إنشاء وتعديل الجداول',en:'Schedules'},
    announcements:{ar:'الإعلانات',en:'Announcements'},
    createAnnouncements:{ar:'إنشاء إعلانات',en:'Announcements'},
    studentLookup:{ar:'صفحة الطلاب',en:'Student Lookup'},
    addTeacher:{ar:'إضافة معلم',en:'Add Teacher'},
    addStudent:{ar:'إضافة طالب',en:'Add Student'},
    addAdmin:{ar:'إضافة إداري',en:'Add Admin'},
    name:{ar:'الاسم',en:'Name'},
    password:{ar:'كلمة المرور',en:'Password'},
    profileImage:{ar:'الصورة الشخصية',en:'Profile Image'},
    delegations:{ar:'التوكيلات',en:'Delegations'},
    newDelegation:{ar:'توكيل جديد',en:'New Delegation'},
    delegationType:{ar:'نوع التوكيل',en:'Delegation Type'},
    typeSubject:{ar:'مادة دراسية',en:'Subject'},
    typeClass:{ar:'صف دراسي',en:'Class'},
    typeStudents:{ar:'طلاب',en:'Students'},
    title:{ar:'العنوان',en:'Title'},
    description:{ar:'الوصف',en:'Description'},
    subjectName:{ar:'اسم المادة',en:'Subject Name'},
    className:{ar:'البرنامج/الصف',en:'Program / Class'},
    selectStudents:{ar:'اختر الطلاب',en:'Select Students'},
    noTeachers:{ar:'لا يوجد معلمين',en:'No teachers'},
    noAdmins:{ar:'لا يوجد إداريين',en:'No admins'},
    newSchedule:{ar:'جدول جديد',en:'New Schedule'},
    scheduleName:{ar:'اسم الجدول',en:'Schedule Name'},
    addColumn:{ar:'إضافة عمود',en:'Add Column'},
    addRow:{ar:'إضافة صف',en:'Add Row'},
    createSchedule:{ar:'إنشاء الجدول',en:'Create Schedule'},
    noSchedules:{ar:'لا توجد جداول بعد',en:'No schedules yet'},
    weekly:{ar:'أسبوعي',en:'Weekly'}, monthly:{ar:'شهري',en:'Monthly'}, daily:{ar:'يومي',en:'Daily'}, seasonal:{ar:'فصلي',en:'Seasonal'},
    newAnnouncement:{ar:'إعلان جديد',en:'New Announcement'},
    announcementTitle:{ar:'عنوان الإعلان',en:'Announcement title'},
    announcementContent:{ar:'نص الإعلان',en:'Announcement text'},
    template:{ar:'القالب',en:'Template'},
    tmplGeneral:{ar:'إعلان عام',en:'General'},
    tmplExam:{ar:'امتحانات',en:'Exams'},
    tmplHoliday:{ar:'إجازة',en:'Holiday'},
    tmplEvent:{ar:'فعالية',en:'Event'},
    tmplUrgent:{ar:'عاجل',en:'Urgent'},
    publish:{ar:'نشر الإعلان',en:'Publish'},
    noAnnouncements:{ar:'لا توجد إعلانات',en:'No announcements'},
    noAnnouncementsB:{ar:'ستظهر هنا إعلانات الإدارة الموجّهة إليك',en:'Announcements addressed to you will appear here'},
    audience:{ar:'الفئة المستهدفة',en:'Audience'},
    audienceHint:{ar:'من بإمكانه رؤية هذا الإعلان؟',en:'Who can see this announcement?'},
    audStudents:{ar:'الطلاب',en:'Students'},
    audTeachers:{ar:'المعلمون',en:'Teachers'},
    audAdmins:{ar:'الإداريون',en:'Admins'},
    audAll:{ar:'الجميع',en:'Everyone'},
    pickAudience:{ar:'اختر فئة واحدة على الأقل',en:'Pick at least one audience'},
    manageGrades:{ar:'إدارة الدرجات',en:'Manage Grades'},
    allStudents:{ar:'جميع الطلاب',en:'All Students'},
    selectStudentView:{ar:'اختر طالباً لإدارة درجاته وسلوكه',en:'Select a student to manage grades and behavior'},
    editGrade:{ar:'تعديل الدرجة',en:'Edit Grade'},
    noStudents:{ar:'لا يوجد طلاب',en:'No students'},
    shareTo:{ar:'مشاركة مع',en:'Share with'},
    students:{ar:'الطلاب',en:'Students'},
    selectAll:{ar:'تحديد الكل',en:'Select all'},
    sent:{ar:'تم الإرسال بنجاح',en:'Sent successfully'},
    addToCloud:{ar:'أضف للسحابة',en:'Add to cloud'},
    shareNow:{ar:'مشاركة الآن',en:'Share now'},
    lookupHint:{ar:'أدخل مفتاح دخول الطالب لعرض ملفه',en:'Enter a student access key to view their file'},
    lookup:{ar:'بحث',en:'Look up'},
    studentNotFound:{ar:'لم يتم العثور على الطالب',en:'Student not found'},
    overview:{ar:'نظرة عامة',en:'Overview'},
    // ---- المنهج والمقررات (التحديث الكبير)
    curriculum:{ar:'المنهج والمقررات',en:'Curriculum'},
    courses:{ar:'المقررات',en:'Courses'},
    myCourses:{ar:'مقرراتي',en:'My Courses'},
    course:{ar:'مقرر',en:'Course'},
    courseName:{ar:'اسم المقرر',en:'Course name'},
    courseCode:{ar:'رمز المقرر',en:'Code'},
    courseLink:{ar:'ملف/رابط المقرر',en:'Course file / link'},
    courseLinkHint:{ar:'رابط ملف المقرر (اختياري)',en:'Course file link (optional)'},
    addCourse:{ar:'إضافة مقرر',en:'Add course'},
    editCourse:{ar:'تعديل المقرر',en:'Edit course'},
    noCourses:{ar:'لا توجد مقررات في هذا الفصل بعد',en:'No courses in this semester yet'},
    noCoursesB:{ar:'ستظهر مقرراتك هنا عند إسنادها من الإدارة',en:'Your courses appear here once assigned'},
    currentSemester:{ar:'الفصل الحالي',en:'Current semester'},
    setCurrentSemester:{ar:'تحديد الفصل الحالي',en:'Set current semester'},
    semesterSaved:{ar:'تم تحديث الفصل الحالي',en:'Current semester updated'},
    diploma:{ar:'الدبلومة',en:'Diploma'},
    semester:{ar:'الفصل',en:'Semester'},
    allDiplomas:{ar:'كل الدبلومات',en:'All diplomas'},
    openLink:{ar:'فتح الملف',en:'Open file'},
    // الإسناد والتوكيل
    assignTeachers:{ar:'إسناد المعلمين',en:'Assign teachers'},
    assignStudents:{ar:'إسناد الطلاب',en:'Enroll students'},
    teachingCourses:{ar:'المواد الموكلة للتدريس',en:'Courses I teach'},
    assignedTeachers:{ar:'المعلمون المسندون',en:'Assigned teachers'},
    enrolledStudents:{ar:'الطلاب المسجّلون',en:'Enrolled students'},
    myDelegatedStudents:{ar:'الطلاب الموكلون إليّ',en:'My students'},
    assignStudentsToTeacher:{ar:'توكيل طلاب للمعلم',en:'Assign students to teacher'},
    none:{ar:'لا أحد بعد',en:'None yet'},
    // الدرجات ثلاثية المكوّن
    participation:{ar:'المشاركة والتكليف',en:'Participation'},
    midterm:{ar:'الاختبار النصفي',en:'Midterm'},
    finalExam:{ar:'الاختبار النهائي',en:'Final'},
    total:{ar:'المجموع',en:'Total'},
    enterGrades:{ar:'إدخال الدرجات',en:'Enter grades'},
    saveDraft:{ar:'حفظ كمسودة',en:'Save draft'},
    confirmGrade:{ar:'تأكيد الدرجة',en:'Confirm grade'},
    confirmGrades:{ar:'تأكيد الدرجات',en:'Confirm grades'},
    confirmed:{ar:'مؤكدة',en:'Confirmed'},
    draft:{ar:'مسودة',en:'Draft'},
    awaitingApproval:{ar:'بانتظار الاعتماد',en:'Awaiting approval'},
    approve:{ar:'اعتماد',en:'Approve'},
    approveAll:{ar:'اعتماد الكل',en:'Approve all'},
    approved:{ar:'معتمدة',en:'Approved'},
    gradeApproval:{ar:'اعتماد الدرجات',en:'Grade approval'},
    pendingApproval:{ar:'درجات بانتظار الاعتماد',en:'Grades awaiting approval'},
    noPending:{ar:'لا توجد درجات بانتظار الاعتماد',en:'No grades awaiting approval'},
    confirmHint:{ar:'بعد التأكيد تُرسل للإدارة لاعتمادها',en:'Once confirmed it is sent to administration for approval'},
    notApprovedYet:{ar:'لم تُعتمد درجاتك بعد',en:'Your grades are not approved yet'},
    notApprovedYetB:{ar:'ستظهر درجاتك فور اعتمادها من الإدارة',en:'Grades appear once approved by administration'},
    // حالة الطالب + الرقم
    studentStatus:{ar:'حالة الطالب',en:'Student status'},
    statusLabel:{ar:'الحالة',en:'Status'},
    statusRegular:{ar:'منتظم',en:'Regular'},
    statusSuspended:{ar:'معلّق',en:'Suspended'},
    statusWithdrawn:{ar:'منقطع',en:'Withdrawn'},
    studentNumber:{ar:'رقم الطالب',en:'Student no.'},
    changeStatus:{ar:'تغيير الحالة',en:'Change status'},
    saved:{ar:'تم الحفظ',en:'Saved'},
    selectCourse:{ar:'اختر مقرراً',en:'Select a course'},
    selectCourseB:{ar:'اختر مقرراً من المواد الموكلة إليك لإدخال درجات طلابه',en:'Pick one of your courses to enter its students\u2019 grades'},
    // ---- إضافة المستخدمين والصور والمجموعات
    addStudent:{ar:'إضافة طالب',en:'Add student'},
    photo:{ar:'الصورة',en:'Photo'},
    uploadPhoto:{ar:'اختيار صورة',en:'Choose photo'},
    changePhoto:{ar:'تغيير الصورة',en:'Change photo'},
    specializations:{ar:'التخصصات',en:'Specializations'},
    specsHint:{ar:'افصل بين التخصصات بفاصلة',en:'Separate with commas'},
    attendanceGroup:{ar:'مجموعة الحضور',en:'Attendance group'},
    weekend:{ar:'نهاية الأسبوع',en:'Weekend'},
    weekday:{ar:'بداية الأسبوع',en:'Weekday'},
    weekendStudent:{ar:'طالب نهاية الأسبوع',en:'Weekend student'},
    weekdayStudent:{ar:'طالب بداية الأسبوع',en:'Weekday student'},
    allGroups:{ar:'كل المجموعات',en:'All groups'},
    courseFile:{ar:'ملف المقرر',en:'Course file'},
    chooseFile:{ar:'اختيار ملف من الجهاز',en:'Choose file'},
    replaceFile:{ar:'استبدال الملف',en:'Replace file'},
    removeFile:{ar:'إزالة الملف',en:'Remove file'},
    openFile:{ar:'فتح الملف',en:'Open file'},
    confirmedHidden:{ar:'تم تأكيد الدرجة وإرسالها للإدارة',en:'Grade confirmed and sent to administration'},
    allConfirmed:{ar:'تم تأكيد جميع الدرجات',en:'All grades confirmed'},
    allConfirmedB:{ar:'لا توجد درجات بانتظار الإدخال في هذا المقرر',en:'No grades pending entry for this course'},
  };

  const L = (lang) => (key) => (STR[key] && STR[key][lang]) || key;
  const pick = (obj, lang) => obj ? (obj[lang] != null ? obj[lang] : obj.ar) : '';

  // ----------------------------------------------------------------- SEED
  const today = new Date();
  const iso = (d) => new Date(d).toISOString();
  const daysAgo = (n) => iso(new Date(today.getTime() - n * 864e5));

  const seedSchedule = {
    columns:['اليوم','08:00 - 09:30','09:45 - 11:15','11:30 - 13:00'],
    rows:[
      ['الأحد','الفقه','الحديث','أصول الفقه'],
      ['الثلاثاء','التفسير','العقيدة','السيرة'],
      ['الخميس','اللغة العربية','مصطلح الحديث','—'],
    ]
  };

  const seed = {
    users: [
      {accessKey:'DIR1', password:'1234', name:'د. عبدالرحمن الفقيه', role:'director', managementSection:'director', phone:'0500000001', email:'director@tamkeen.edu', img:null},
      {accessKey:'K100', password:'1234', name:'أ. يسرى المنصور', role:'management', managementSection:'yousra', phone:'0500000002', email:'yousra@tamkeen.edu', img:null},
      {accessKey:'K101', password:'1234', name:'أ. أحمد الزهراني', role:'management', managementSection:'ahmed', phone:'0500000003', email:'ahmed@tamkeen.edu', img:null},
      {accessKey:'T100', password:'1234', name:'أ. خالد العتيبي', role:'teacher', specializations:['الفقه','أصول الفقه'], phone:'0500000010', email:'khaled@tamkeen.edu', img:null},
      {accessKey:'T101', password:'1234', name:'أ. منى السالم', role:'teacher', specializations:['اللغة العربية','النحو'], phone:'0500000011', email:'mona@tamkeen.edu', img:null},
      {accessKey:'S100', password:'1234', name:'محمد العمري', role:'student', academicYear:'دبلوم السنة النبوية — السنة الأولى', phone:'0500000020', email:'m.alamri@mail.com', img:null},
      {accessKey:'S101', password:'1234', name:'سارة القحطاني', role:'student', academicYear:'دبلوم اللغة العربية — السنة الأولى', phone:'0500000021', email:'sara.q@mail.com', img:null},
      {accessKey:'S102', password:'1234', name:'عبدالله الشهري', role:'student', academicYear:'دبلوم التمريض — السنة الثانية', phone:'0500000022', email:'a.alshehri@mail.com', img:null},
    ],
    delegations: [
      {id:'d1', teacherId:'T100', type:'subject', title:'تدريس مادة الفقه', description:'متابعة طلاب السنة الأولى في مادة الفقه وأصوله.', subjectName:'الفقه', className:'دبلوم السنة النبوية', studentIds:['S100','S101'], status:'active', assignedBy:'K100', assignedAt:daysAgo(20)},
      {id:'d2', teacherId:'T101', type:'students', title:'توكيل طلاب', description:'متابعة الطالب في اللغة العربية.', subjectName:'اللغة العربية', className:'دبلوم اللغة العربية', studentIds:['S102'], status:'active', assignedBy:'K100', assignedAt:daysAgo(12)},
    ],
    grades: [],
    assignments: [],
    behaviorScores: {},
    schedules: [],
    announcements: [],
    sharedItems: [],
    cloudItems: [],
    _seq: { grade:100, assignment:100, announcement:100, shared:100 },
  };

  // public content (bilingual)
  const diplomas = [
    { id:'sunnah', icon:'scroll', color:'#8C6F47',
      name:{ar:'دبلوم السنة النبوية',en:'Prophetic Sunnah Diploma'},
      desc:{ar:'دراسة متعمّقة في علوم الحديث والسيرة والفقه، بإشراف نخبة من المتخصصين.',en:'In-depth study of hadith sciences, the Prophetic biography and fiqh, supervised by specialists.'},
      duration:{ar:'سنتان',en:'2 Years'}, credits:{ar:'72 ساعة',en:'72 hours'}, days:{ar:'الأحد · الثلاثاء · الخميس',en:'Sun · Tue · Thu'} },
    { id:'arabic', icon:'languages', color:'#B68A3E',
      name:{ar:'دبلوم اللغة العربية',en:'Arabic Language Diploma'},
      desc:{ar:'تمكين الطالب من النحو والصرف والبلاغة والأدب، نظرياً وتطبيقياً.',en:'Mastering grammar, morphology, rhetoric and literature — theory and practice.'},
      duration:{ar:'سنتان',en:'2 Years'}, credits:{ar:'64 ساعة',en:'64 hours'}, days:{ar:'الاثنين · الأربعاء',en:'Mon · Wed'} },
    { id:'nursing', icon:'heart', color:'#A98F66',
      name:{ar:'دبلوم التمريض',en:'Nursing Diploma'},
      desc:{ar:'إعداد كوادر تمريضية مؤهّلة بمهارات سريرية عملية وتدريب ميداني.',en:'Preparing qualified nursing staff with practical clinical skills and field training.'},
      duration:{ar:'سنتان ونصف',en:'2.5 Years'}, credits:{ar:'90 ساعة',en:'90 hours'}, days:{ar:'الجمعة · الأحد',en:'Fri · Sun'} },
  ];

  const leadership = [
    { group:'board',
      title:{ar:'مجلس الإدارة',en:'Board of Directors'},
      members:[
        { img:'assets/man-img1.jpg', woman:false, name:{ar:'الشيخ محمد إدريس البكر',en:'Sheikh Mohammed Idris Al-Bakr'}, position:{ar:'رئيس مجلس الإدارة',en:'Chairman of the Board'}, specialization:{ar:'إدارة الأعمال',en:'Business Administration'}, email:'M.albakur.25@gmail.com', phone:'+966 582 613 355 · +234 902 207 2006' },
        { img:'assets/man-img2.jpg', woman:false, name:{ar:'الشيخ علي عباس برناوي',en:'Sheikh Ali Abbas Barnawi'}, position:{ar:'نائب رئيس مجلس الإدارة',en:'Vice Chairman'}, specialization:{ar:'التربية والتعليم',en:'Education'}, email:'Ali-abbas7@hotmail.com', phone:'+234 802 661 2468' },
      ] },
    { group:'executive',
      title:{ar:'الفريق التنفيذي',en:'Executive Team'},
      members:[
        { img:'assets/man-img3.jpg', woman:false, name:{ar:'الشيخ عمار أبو بكر محمد',en:'Sheikh Ammar Abu Bakr Mohammed'}, position:{ar:'المدير التنفيذي',en:'Executive Director'}, specialization:{ar:'إدارة الأعمال',en:'Business Administration'}, email:'abuhushaim@gmail.com', phone:'+234 806 941 7376' },
        { img:'assets/man-img4.jpg', woman:true, name:{ar:'الدكتورة أسرار بشير عثمان',en:'Dr. Asrar Bashir Othman'}, position:{ar:'نائب المدير التنفيذي',en:'Deputy Executive Director'}, specialization:{ar:'المالية والمحاسبة',en:'Finance & Accounting'}, email:'Srosh22bash@gmail.com', phone:'+234 902 165 5552' },
        { img:'assets/man-img5.jpg', woman:false, name:{ar:'الشيخ أحمد حسن عبدالقادر',en:'Sheikh Ahmed Hassan Abdulqadir'}, position:{ar:'السكرتارية والإعلام',en:'Secretariat & Media'}, specialization:{ar:'التسويق',en:'Marketing'}, email:'hassanahmad48@gmail.com', phone:'+234 806 844 2718' },
      ] },
    { group:'academic',
      title:{ar:'الفريق الأكاديمي',en:'Academic Team'},
      members:[
        { img:'assets/man-img6.jpg', woman:true, name:{ar:'الدكتورة يسرا محمود أحمد',en:'Dr. Yousra Mahmoud Ahmed'}, position:{ar:'الشؤون التعليمية',en:'Educational Affairs'}, specialization:{ar:'التربية والتعليم',en:'Education'}, email:'sout791@gmail.com', phone:'+234 701 378 2431' },
      ] },
  ];

  // verses & supplications for the scrolling banner
  const bannerVerses = {
    ar: [
      'وَقُل رَّبِّ زِدْنِي عِلْمًا',
      'اللَّهُمَّ بَارِكْ لَنَا فِيمَا عَلَّمْتَنَا وَعَلِّمْنَا مَا يَنْفَعُنَا',
      'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
      'وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا',
      'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي',
      'وَفَوْقَ كُلِّ ذِي عِلْمٍ عَلِيمٌ',
      'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    ],
    en: [
      'And say: My Lord, increase me in knowledge',
      'O Allah, bless us in what You have taught us and teach us what benefits us',
      'Seeking knowledge is an obligation upon every Muslim',
      'And whoever is given wisdom has been given much good',
      'O Allah, benefit me with what You have taught me and teach me what benefits me',
      'And above every possessor of knowledge is one more knowing',
      'O Allah, help me to remember You, thank You, and worship You well',
    ],
  };

  // ----------------------------------------------------------------- ICONS
  const I = {
    globe:<React.Fragment><circle cx="12" cy="12" r="10"/><path d="M2 12h20"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></React.Fragment>,
    languages:<React.Fragment><path d="m5 8 6 6"/><path d="m4 14 6-6 2-3"/><path d="M2 5h12"/><path d="M7 2h1"/><path d="m22 22-5-10-5 10"/><path d="M14 18h6"/></React.Fragment>,
    user:<React.Fragment><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></React.Fragment>,
    users:<React.Fragment><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></React.Fragment>,
    userCheck:<React.Fragment><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="m16 11 2 2 4-4"/></React.Fragment>,
    gradCap:<React.Fragment><path d="M22 10 12 5 2 10l10 5 10-5z"/><path d="M6 12v5c0 1 2 3 6 3s6-2 6-3v-5"/></React.Fragment>,
    lock:<React.Fragment><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></React.Fragment>,
    key:<React.Fragment><circle cx="7.5" cy="15.5" r="5.5"/><path d="m21 2-9.6 9.6"/><path d="m15.5 7.5 3 3L22 7l-3-3"/></React.Fragment>,
    eye:<React.Fragment><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z"/><circle cx="12" cy="12" r="3"/></React.Fragment>,
    eyeOff:<React.Fragment><path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/><path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"/><path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"/><path d="m2 2 20 20"/></React.Fragment>,
    arrowLeft:<React.Fragment><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></React.Fragment>,
    arrowRight:<React.Fragment><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></React.Fragment>,
    inbox:<React.Fragment><path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></React.Fragment>,
    book:<React.Fragment><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></React.Fragment>,
    fileText:<React.Fragment><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M16 13H8"/><path d="M16 17H8"/><path d="M10 9H8"/></React.Fragment>,
    star:<React.Fragment><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></React.Fragment>,
    clock:<React.Fragment><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></React.Fragment>,
    check:<React.Fragment><path d="M20 6 9 17l-5-5"/></React.Fragment>,
    checkCircle:<React.Fragment><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></React.Fragment>,
    calendar:<React.Fragment><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/></React.Fragment>,
    award:<React.Fragment><circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/></React.Fragment>,
    mail:<React.Fragment><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-10 5L2 7"/></React.Fragment>,
    phone:<React.Fragment><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/></React.Fragment>,
    chevronDown:<React.Fragment><path d="m6 9 6 6 6-6"/></React.Fragment>,
    chevronUp:<React.Fragment><path d="m18 15-6-6-6 6"/></React.Fragment>,
    chevronLeft:<React.Fragment><path d="m15 18-6-6 6-6"/></React.Fragment>,
    chevronRight:<React.Fragment><path d="m9 18 6-6-6-6"/></React.Fragment>,
    download:<React.Fragment><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><path d="M12 15V3"/></React.Fragment>,
    logout:<React.Fragment><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><path d="M21 12H9"/></React.Fragment>,
    cloud:<React.Fragment><path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9z"/></React.Fragment>,
    trash:<React.Fragment><path d="M3 6h18"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/></React.Fragment>,
    x:<React.Fragment><path d="M18 6 6 18"/><path d="m6 6 12 12"/></React.Fragment>,
    edit:<React.Fragment><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4z"/></React.Fragment>,
    plus:<React.Fragment><path d="M5 12h14"/><path d="M12 5v14"/></React.Fragment>,
    search:<React.Fragment><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></React.Fragment>,
    megaphone:<React.Fragment><path d="m3 11 18-5v12L3 14v-3z"/><path d="M11.6 16.8a3 3 0 1 1-5.8-1.6"/></React.Fragment>,
    upload:<React.Fragment><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><path d="M12 3v12"/></React.Fragment>,
    briefcase:<React.Fragment><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></React.Fragment>,
    clipboard:<React.Fragment><rect x="8" y="2" width="8" height="4" rx="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="M12 11h4"/><path d="M12 16h4"/><path d="M8 11h.01"/><path d="M8 16h.01"/></React.Fragment>,
    send:<React.Fragment><path d="m22 2-7 20-4-9-9-4z"/><path d="M22 2 11 13"/></React.Fragment>,
    camera:<React.Fragment><path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/></React.Fragment>,
    bell:<React.Fragment><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/></React.Fragment>,
    menu:<React.Fragment><path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/></React.Fragment>,
    mapPin:<React.Fragment><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/></React.Fragment>,
    sparkles:<React.Fragment><path d="m12 3 1.9 5.8 5.8 1.9-5.8 1.9L12 18l-1.9-5.4L4.3 10.7l5.8-1.9z"/></React.Fragment>,
    grid:<React.Fragment><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/></React.Fragment>,
    info:<React.Fragment><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></React.Fragment>,
    alert:<React.Fragment><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3z"/><path d="M12 9v4"/><path d="M12 17h.01"/></React.Fragment>,
    building:<React.Fragment><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01"/><path d="M16 6h.01"/><path d="M12 6h.01"/><path d="M12 10h.01"/><path d="M12 14h.01"/><path d="M16 10h.01"/><path d="M16 14h.01"/><path d="M8 10h.01"/><path d="M8 14h.01"/></React.Fragment>,
    scroll:<React.Fragment><path d="M8 21h12a2 2 0 0 0 2-2v-2H10v2a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v3h4"/><path d="M19 17V5a2 2 0 0 0-2-2H4"/></React.Fragment>,
    heart:<React.Fragment><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7z"/><path d="M3.22 12H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"/></React.Fragment>,
    target:<React.Fragment><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></React.Fragment>,
    compass:<React.Fragment><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></React.Fragment>,
    gem:<React.Fragment><path d="M6 3h12l4 6-10 13L2 9z"/><path d="M11 3 8 9l4 13 4-13-3-6"/><path d="M2 9h20"/></React.Fragment>,
    shield:<React.Fragment><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></React.Fragment>,
    layers:<React.Fragment><path d="m12 2 9 5-9 5-9-5 9-5z"/><path d="m3 12 9 5 9-5"/><path d="m3 17 9 5 9-5"/></React.Fragment>,
    party:<React.Fragment><path d="M5.8 11.3 2 22l10.7-3.79"/><path d="M4 3h.01"/><path d="M22 8h.01"/><path d="M15 2h.01"/><path d="M22 20h.01"/><path d="m11 13 9-9"/></React.Fragment>,
    calDays:<React.Fragment><rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4"/><path d="M8 2v4"/><path d="M3 10h18"/><path d="M8 14h.01"/><path d="M12 14h.01"/><path d="M16 14h.01"/><path d="M8 18h.01"/><path d="M12 18h.01"/></React.Fragment>,
    calculator:<React.Fragment><rect x="4" y="2" width="16" height="20" rx="2"/><line x1="8" y1="6" x2="16" y2="6"/><line x1="16" y1="14" x2="16" y2="18"/><path d="M16 10h.01"/><path d="M12 10h.01"/><path d="M8 10h.01"/><path d="M12 14h.01"/><path d="M8 14h.01"/><path d="M12 18h.01"/><path d="M8 18h.01"/></React.Fragment>,
  };
  // alias mapping for announcement templates
  I.general = I.info; I.exam = I.book; I.holiday = I.calDays; I.event = I.party; I.urgent = I.alert;

  function Icon({ name, size=18, color='currentColor', sw=1.8, style, className }) {
    return (
      <svg className={className} width={size} height={size} viewBox="0 0 24 24" fill="none"
        stroke={color} strokeWidth={sw} strokeLinecap="round" strokeLinejoin="round" style={style}>
        {I[name] || I.info}
      </svg>
    );
  }

  // ----------------------------------------------------------------- HELPERS
  const fmtDate = (d, lang) => {
    if (!d) return '—';
    try { return new Date(d).toLocaleDateString(lang === 'ar' ? 'ar-EG' : 'en-GB', { year:'numeric', month:'short', day:'numeric' }); }
    catch { return '—'; }
  };
  const initials = (name='') => (name.replace(/^[أ-ي]\.\s*/, '').trim().charAt(0) || '؟');
  const roleLabel = (role, lang) => {
    const m = { student:STR.student, teacher:STR.teacher, management:STR.admin, director:STR.director };
    return m[role] ? m[role][lang] : role;
  };
  const deepClone = (o) => JSON.parse(JSON.stringify(o));

  window.TC = { theme, roleColor, STR, L, pick, seed, diplomas, leadership, bannerVerses, Icon, fmtDate, initials, roleLabel, deepClone };
})();
